import { ArrowLeft, Download, FileText, HelpCircle } from 'lucide-react';
import type { Metadata } from 'next';
import Link from 'next/link';
import { siteConfig } from '@/shared/config/site';

export const metadata: Metadata = {
	title:
		'Free Printable String Art Radial Pin Templates PDF (100, 200, 300 Pins)',
	description:
		'Download free printable circular string art pin templates in PDF format. Scaled radial patterns with pin markings for 100, 200, and 300 nails.',
	keywords: [
		'free string art printable templates',
		'circular string art pattern pdf',
		'string art pin circle template',
		'string art nail pattern pdf',
		'100 pins string art template',
		'200 pins string art template',
		'300 pins string art template',
		'diy string art circular guide',
	],
	alternates: {
		canonical: '/en/templates',
		languages: {
			es: '/plantillas',
			en: '/en/templates',
			'x-default': '/plantillas',
		},
	},
	openGraph: {
		title:
			'Free Printable String Art Radial Pin Templates PDF (100, 200, 300 Pins)',
		description:
			'Download free printable circular pin templates for string art in PDF format. Precise radial patterns for 100, 200, and 300 nails.',
		url: `${siteConfig.url}/en/templates`,
		siteName: siteConfig.name,
		type: 'website',
	},
};

const TEMPLATES = [
	{
		pins: 100,
		title: '100 Pins Template (Beginner)',
		subtitle: 'Ideal for 30–40 cm boards with thicker thread',
		desc: 'Recommended for crafters starting out with string art. Generous spacing between pins makes hammer alignment and threading easy.',
		file: '/templates/100-pins-template.pdf',
		size: '405 KB',
		linesRecommended: '1,500 – 2,500 lines',
		badge: 'Beginner',
	},
	{
		pins: 200,
		title: '200 Pins Template (Standard)',
		subtitle: 'Optimal balance for portraits and wall decor',
		desc: 'Our most popular template. Provides rich tonal contrast and sharp definition for faces, logos, and graphic silhouettes on 40–50 cm boards.',
		file: '/templates/200-pins-template.pdf',
		size: '413 KB',
		linesRecommended: '2,500 – 4,000 lines',
		badge: 'Most Popular',
	},
	{
		pins: 300,
		title: '300 Pins Template (High Definition)',
		subtitle: 'For hyper-realistic 50–65 cm exhibition pieces',
		desc: 'Tailored for experienced crafters and artists. Captures micro-details and continuous photographic gradients using fine silk or cotton thread.',
		file: '/templates/300-pins-template.pdf',
		size: '421 KB',
		linesRecommended: '3,500 – 5,500 lines',
		badge: 'Professional',
	},
];

export default function EnglishTemplatesPage() {
	return (
		<main className='min-h-screen bg-background px-4 py-12 sm:px-8'>
			<div className='mx-auto max-w-4xl space-y-12'>
				<nav className='flex items-center justify-between'>
					<Link
						href='/en'
						className='inline-flex items-center gap-1.5 font-medium text-muted-foreground text-xs transition-colors hover:text-foreground'
					>
						<ArrowLeft className='size-3.5' /> Back to Studio
					</Link>
					<Link
						href='/plantillas'
						className='rounded-md border border-border/70 px-2 py-0.5 font-semibold text-muted-foreground text-xs hover:text-foreground'
					>
						Español (ES)
					</Link>
				</nav>

				<header className='space-y-3'>
					<div className='inline-flex items-center gap-2 rounded-full border border-primary/20 bg-primary/10 px-3 py-1 font-medium text-primary text-xs'>
						<FileText className='size-3.5' /> Free Printable Resources
					</div>
					<h1 className='font-bold font-serif text-3xl text-foreground sm:text-4xl'>
						Printable Circular String Art Pin Templates (PDF)
					</h1>
					<p className='text-muted-foreground text-sm leading-relaxed sm:text-base'>
						Download our high-precision radial nail templates ready to print and
						place on your wooden board. All templates place{' '}
						<strong>Pin 0 at the 12:00 clock position</strong> to match the
						step-by-step instructions generated by our online studio.
					</p>
				</header>

				<section className='grid gap-6 sm:grid-cols-3'>
					{TEMPLATES.map((tmpl) => (
						<article
							key={tmpl.pins}
							className='flex flex-col justify-between rounded-xl border border-border/60 bg-card/40 p-5 shadow-xs transition-colors hover:border-primary/40'
						>
							<div className='space-y-3'>
								<div className='flex items-center justify-between'>
									<span className='rounded-md bg-secondary px-2 py-0.5 font-medium text-secondary-foreground text-xs'>
										{tmpl.badge}
									</span>
									<span className='font-mono text-muted-foreground text-xs'>
										{tmpl.size}
									</span>
								</div>
								<div>
									<h2 className='font-bold text-foreground text-lg'>
										{tmpl.pins} Pins
									</h2>
									<p className='font-medium text-primary text-xs'>
										{tmpl.subtitle}
									</p>
								</div>
								<p className='text-muted-foreground text-xs leading-relaxed'>
									{tmpl.desc}
								</p>
								<div className='border-border/40 border-t pt-2 text-muted-foreground text-xs'>
									Recommended lines: <strong>{tmpl.linesRecommended}</strong>
								</div>
							</div>

							<div className='mt-6 pt-2'>
								<a
									href={tmpl.file}
									download
									className='inline-flex w-full items-center justify-center gap-2 rounded-lg bg-primary py-2.5 font-medium text-primary-foreground text-xs shadow-xs transition-opacity hover:opacity-90'
								>
									<Download className='size-3.5' /> Download PDF
								</a>
							</div>
						</article>
					))}
				</section>

				<section className='space-y-4 rounded-xl border border-border/60 bg-muted/20 p-6'>
					<h2 className='flex items-center gap-2 font-semibold text-base text-foreground'>
						<HelpCircle className='size-4 text-primary' /> Printing & Crafting
						Instructions
					</h2>
					<ol className='list-decimal space-y-2 pl-5 text-muted-foreground text-xs leading-relaxed sm:text-sm'>
						<li>
							<strong>Print Settings:</strong> In your PDF viewer, make sure to
							select <em>"Actual Size"</em> or <em>"Scale 100%"</em>. Do not use
							"Fit to Page" so radial distances remain exact.
						</li>
						<li>
							<strong>Mount Template:</strong> Tape the printed sheet flat onto
							your round or square wooden board (MDF or birch plywood) using
							masking tape.
						</li>
						<li>
							<strong>Nail Placement:</strong> Drive a small headless pin or
							wire brad perpendicularly into each marked black dot. Ensure{' '}
							<strong>Pin 0</strong> is positioned at the top (12 o'clock).
						</li>
						<li>
							<strong>Remove Paper:</strong> Once all pins are hammered, gently
							tear the paper away from the board.
						</li>
						<li>
							<strong>Weave Thread:</strong> Open the{' '}
							<Link href='/en' className='text-primary underline'>
								String Art Studio
							</Link>
							, upload your photo, and follow the animated sequence.
						</li>
					</ol>
				</section>
			</div>
		</main>
	);
}
